package com.example.chowdi.qremind.Customer;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.example.chowdi.qremind.R;
import com.example.chowdi.qremind.utils.Constants;
import com.firebase.client.Firebase;

import java.util.HashMap;
import java.util.Map;

public class CustomerGetQueue extends AppCompatActivity {
    TextView vendorName;
    Button getQueueBtn;
    private String shop_name;
    private String customer_id;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_getqueuenumber);
        vendorName = (TextView)findViewById(R.id.getqueueno_from_vendor);
        getQueueBtn = (Button)findViewById(R.id.getqueuebtn);

        shop_name = getIntent().getExtras().getString("SHOP_NAME");
        customer_id = getIntent().getExtras().getString("CUSTOMER_ID");
        vendorName.setText(shop_name);
        getQueueBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onClickGetQueue(v);
            }
        });
    }

    /**
     * Inserts into shop queue node,and customer current queue
     * @param view
     */
    public void onClickGetQueue(View view){
        Firebase ref = new Firebase(Constants.FIREBASE_SHOPS+"/"+getIntent().getExtras().getString("SHOP_NAME")+"/queues");
        Firebase custRef = new Firebase(Constants.FIREBASE_CUSTOMER+"/"+getIntent().getExtras().getString("CUSTOMER_ID")+"/current_queue");
        //add shop queue
        Map<String, Object> map = new HashMap<String, Object>();
        map.put(customer_id, true);
        ref.updateChildren(map);
        //add cust current queue
        Map<String, Object> map2 = new HashMap<String, Object>();
        map2.put("no", 5);
        map2.put(shop_name, true);
        custRef.setValue(map2);
        //we could use .push() and save the uniq ID generated by firebase?

        //start customer currently serving activity
        Intent intent = new Intent(getBaseContext(), CustomerCurrentServing.class);
        intent.putExtra("SHOP_NAME",shop_name);
        intent.putExtra("CUSTOMER_ID", customer_id);
        startActivity(intent);
    }
}
